name: hlservice-part2
services:
  hl-database:
    image: hldatabase
    ports:
      - 5432:${DB_CONTAINER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: ${DB_CONTAINER_NAME}
    networks:
      - networkHl
    restart: always

  hl-backend:
    image: hlservice
    ports:
      - ${PORT}:${PORT}
      - 5555:5555
    volumes:
      - ./:/app
    depends_on:
      - hl-database
    networks:
      - networkHl
    restart: always

networks:
  networkHl:
